name: Semgrep

on:
  pull_request: {}
  push:
    branches: ["master"]

jobs:
  semgrep:
    name: Semgrep
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci
        env:
           SEMGREP_RULES: p/default
